PROJECT=jdksavb
PROJECT_NAME=jdksavb
PROJECT_VERSION?=20140503
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=BSD
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2014
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://jdksavb.statusbar.com/
PROJECT_IDENTIFIER=org.statusbar.jdksavb
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

JDKSAVDECC_C_DIR_SHELL:=$(shell cd $(PROJECT_TOP_DIR)/../jdksavdecc-c && pwd)

JDKSAVDECC_C_DIR?=$(JDKSAVDECC_C_DIR_SHELL)

TOP_LIB_DIRS+=$(JDKSAVDECC_C_DIR)

CONFIG_TOOLS=

INCLUDES+=$(JDKSAVDECC_C_DIR)/include

COMPILE_FLAGS+=-Wall -W


